name: Sed-replacer
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "SnowGirl"
          replace: "DaisyX"
      - name: Pull All Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Welcome to Daisy X'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: aryazakaria01
          commit_user_email: ardianrazak7107@gmail.com
          commit_author: aryazakaria01 <ardianrazak7107@gmail.com>
